apiVersion: apps/v1
kind: Deployment
metadata:
  name: salon-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: salon-frontend
  template:
    metadata:
      labels:
        app: salon-frontend
    spec:
      containers:
      - name: salon-frontend
        image: dikshant012/salon-frontend:latest
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: salon-frontend
  ports:
    - port: 8501
      targetPort: 8501
      nodePort: 32684
